-- Таблица пользователей (с паролями в открытом виде для админа)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'student'
);

-- Создаем первого администратора (если его еще нет)
INSERT INTO users (username, password, role) 
VALUES ('admin', 'admin123', 'admin') 
ON CONFLICT (username) DO NOTHING;

-- Таблица доступов к тестам
CREATE TABLE IF NOT EXISTS test_access (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  test_key TEXT NOT NULL,
  start_time TIMESTAMP WITH TIME ZONE NOT NULL,
  end_time TIMESTAMP WITH TIME ZONE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE
);

-- Таблица с результатами пройденных тестов
CREATE TABLE IF NOT EXISTS results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  test_name TEXT NOT NULL,
  score INTEGER NOT NULL,
  total INTEGER NOT NULL,
  percentage NUMERIC NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Таблица для хранения базы вопросов
CREATE TABLE IF NOT EXISTS questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  test_key TEXT NOT NULL,
  q TEXT NOT NULL,
  a JSONB NOT NULL,
  c INTEGER NOT NULL
);
